# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 843d0c64abad40ee56116bb3f0b9c61a1b5f11764a5834d2edd9508be84e80c24932c5cc9b0b442442d3a486fff04e487c8e3e091499d817b973a7e7b45866d0

test:
  secret_key_base: 20d622257a01214bf2e2e9d8b75ae2a39205b953bfb821f1bdf70153acf8bbf255fd08a3a48ca838d1f7745dba02cbdb04e16b0a94bdd79237593866f0fa0ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
